dependencies:
- name: mongodb
  version: 4.3.10
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: mongodb.enabled
- name: postgresql
  version: 0.9.5
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: postgresql.enabled
- name: helm-toolkit
  repository: http://localhost:8879/charts
  version: 0.1.0
