apiVersion: v2
appVersion: 7.77.11
dependencies:
- name: helm-toolkit
  repository: file://../deps/helm-toolkit
  version: ">= 0.1.0"
description: Universal Repository Manager supporting all major packaging formats,
  build tools and CI servers.
home: https://www.jfrog.com/artifactory/
icon: https://raw.githubusercontent.com/jfrog/charts/master/stable/artifactory-ha/logo/artifactory-logo.png
keywords:
- artifactory
- jfrog
- devops
kubeVersion: '>= 1.19.0-0'
maintainers:
- email: installers@jfrog.com
  name: Chart Maintainers at JFrog
name: artifactory-ha
sources:
- https://github.com/jfrog/charts
type: application
version: 107.77.11
