apiVersion: v2
appVersion: 2.9.2
description: A Helm chart for JFrog Distribution
home: https://jfrog.com/distribution/
icon: https://raw.githubusercontent.com/jfrog/charts/master/stable/distribution/logo/distribution-logo.png
keywords:
- distribution
- jfrog
maintainers:
- email: installers@jfrog.com
  name: Chart Maintainers at JFrog
name: distribution
sources:
- https://github.com/jfrog/charts
type: application
version: 102.9.3
