apiVersion: v2
appVersion: 2.33.2
dependencies:
- name: helm-toolkit
  repository: file://../deps/helm-toolkit
  version: ">= 0.1.0"
description: A Helm chart for JFrog Distribution
home: https://jfrog.com/distribution/
icon: https://raw.githubusercontent.com/jfrog/charts/master/stable/distribution/logo/distribution-logo.png
keywords:
- distribution
- jfrog
kubeVersion: '>= 1.19.0-0'
maintainers:
- email: installers@jfrog.com
  name: Chart Maintainers at JFrog
name: distribution
sources:
- https://github.com/jfrog/charts
type: application
version: 102.33.2
