{{- if .Values.database.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "distribution.fullname" . }}-database-connection
  labels:
    app: {{ template "distribution.name" . }}
    chart: {{ template "distribution.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: {{ .Values.distribution.name }}
type: Opaque
data:
  db-password: {{ .Values.database.password | b64enc | quote }}
{{- end }}
