{{- if .Values.ingress.enabled -}}
{{- $serviceName := include "distribution.fullname" . -}}
{{- $servicePort := .Values.distribution.externalPort -}}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ template "distribution.fullname" . }}
  labels:
    app: {{ template "distribution.name" . }}
    chart: {{ template "distribution.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: {{ .Values.distribution.name }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  backend:
    serviceName: {{ $serviceName }}
    servicePort: {{ $servicePort }}
{{- if .Values.ingress.hosts }}
  rules:
  {{- range $host := .Values.ingress.hosts }}
  - host: {{ $host | quote }}
    http:
      paths:
        - path: /
          {{- if (semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion) }}
          pathType: ImplementationSpecific
          {{- end }}
          backend:
          {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
            service:
              name: {{ $serviceName }}
              port:
                {{- if or (kindIs "int" $servicePort) (regexMatch "^[0-9]{1,5}$" $servicePort) }}
                number: {{ $servicePort | int }}
                {{- else }}
                name: {{ $servicePort | quote }}
                {{- end }}
          {{- else }}
            serviceName: {{ $serviceName }}
            servicePort: {{ $servicePort }}
          {{- end }}
  {{- end -}}
{{- end -}}
  {{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}

