{{- $envAll := . }}

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dindproxy
  namespace: jenkins-nodes
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: dindproxy
    spec:
      containers:
      - name: dindproxy
        image: {{ .Values.images.tags.dind }}
        imagePullPolicy: {{ .Values.images.pull_policy }}
        args:
          - dockerd
          - --storage-driver=overlay2
          - -H unix:///var/run/dindproxy/docker.sock
        {{- if $envAll.Values.pod.env }}
        env:
          {{- range $envAll.Values.pod.env }}
          - name: {{ .name | quote }}
            value: {{ .value | quote }}
          {{- end }}
        {{- end }}
        securityContext:
          privileged: true
        volumeMounts:
        - name: varlibdockerproxy
          mountPath: /var/lib/dockerproxy
        - name: rundindproxy
          mountPath: /var/run/dindproxy
      nodeSelector:
        {{ .Values.labels.dind.node_selector_key }}: {{ .Values.labels.dind.node_selector_value }}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlibdockerproxy
        emptyDir: {}
      - name: rundindproxy
        hostPath:
          path: /var/run/dindproxy/
