{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: jenkins
    chart: jenkins
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: jenkins-nodes-role
  namespace: {{ .Values.jenkinsNodes.namespace }}
rules:
{{ toYaml .Values.rbac.role.rules }}
{{- end }}
