{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: jenkins
    chart: jenkins
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: jenkins-nodes-rolebindings
  namespace: {{ .Values.jenkinsNodes.namespace}}
subjects:
- kind: ServiceAccount
  name: jenkins-api
  namespace: {{ .Values.jenkinsNodes.service.namespace }}
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: jenkins-nodes-role
{{- end }}
