{{- if and .Values.manifests.job_create_namespaces .Values.manifests.certificates }}
{{- $envAll := . }}

{{- $serviceAccountName := printf "create-namespace-%s" .Release.Name }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: copy-certificate-to-agent
  namespace: {{ .Values.jenkinsNodes.service.namespace }}
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
  template:
    metadata:
      annotations:
{{ dict "envAll" $envAll "podName" "copy-certificate-to-agent" "containerNames" (list "copy-certificate-to-agent") | include "helm-toolkit.snippets.kubernetes_mandatory_access_control_annotation" | indent 8 }}
    spec:
      restartPolicy: Never
      serviceAccount: {{ $serviceAccountName }}
      containers:
      - name: copy-certificate-to-agent
        image: {{ .Values.images.tags.namespace_creator }}
        imagePullPolicy: {{ .Values.images.pull_policy }}
        command: ["/bin/sh","-c", "kubectl get secret jenkins-internal-tls -n {{ .Values.jenkinsNodes.service.namespace }} -o json | jq '{apiVersion,data,kind,metadata,type} | .metadata |= {namespace, name} | .data |= {\"ca.crt\"}' | sed 's/\"namespace\": \".*\"/\"namespace\": \"{{ .Values.jenkinsNodes.namespace }}\"/' | sed 's/\"type\": \".*\"/\"type\": \"Opaque\"/' | kubectl apply -f -"]
{{- end -}}
