{{- $envAll := . }}
{{- $jobName := printf "ldap-credentials-update-%s" .Release.Name }}
{{- $serviceAccountName := printf "create-namespace-%s" .Release.Name }}
{{- $securityRealm := .Values.conf.config.jenkins.securityrealm -}}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $jobName }}
  namespace: {{ .Values.jenkinsNodes.service.namespace }}
  annotations:
    "helm.sh/hook": "pre-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
  template:
    metadata:
      annotations:
{{ dict "envAll" $envAll "podName" "update-ldap-credentials" "containerNames" (list "update-ldap-credentials") | include "helm-toolkit.snippets.kubernetes_mandatory_access_control_annotation" | indent 8 }}
    spec:
      restartPolicy: Never
      serviceAccount: {{ $serviceAccountName }}
      containers:
      - name: update-ldap-credentials
        image: {{ .Values.images.tags.jenkins }}
        imagePullPolicy: {{ .Values.images.pull_policy }}
        command: 
          - /bin/sh
          - -c
          - >
            kubectl exec jenkins-api-0 -n {{ .Values.jenkinsNodes.service.namespace }} -c jenkins -- bash -c
            'cp /var/jenkins_home/config.xml /var/jenkins_home/config.xml_before_ldap_credentials_update &&
            echo \"Updating LDAP manager credentials\" &&
            sed -i -e \"s/<managerDN>.*<\/managerDN>/<managerDN>{{ $securityRealm.manager_dn }}<\/managerDN>/\" /var/jenkins_home/config.xml; &&
            sed -i -e \"s/<managerPasswordSecret>.*<\/managerPasswordSecret>/<managerPasswordSecret>{{ $securityRealm.password }}<\/managerPasswordSecret>/\" /var/jenkins_home/config.xml; &&
            echo \"Following changes are made in config.xml file\" && ( diff /var/jenkins_home/config.xml_before_ldap_credentials_update /var/jenkins_home/config.xml || true )'
