{{- $envAll := . }}

{{- $serviceAccountName := printf "create-namespace-%s" .Release.Name }}
{{- $DeletePlugins := printf "check-plugins-%s" .Release.Name }}
{{- $podmac := dict "check-plugins" "runtime/default" -}}
{{- if hasKey $envAll.Values.pod "mandatory_access_control" -}}
{{- if hasKey $envAll.Values.pod.mandatory_access_control "type" -}}
{{- $macType := $envAll.Values.pod.mandatory_access_control.type -}}
{{- if $macType -}}
{{- if eq $macType "apparmor" -}}
{{- if not (hasKey $envAll.Values.pod.mandatory_access_control $DeletePlugins) -}}
{{- $envAll.Values.pod.mandatory_access_control.$DeletePlugins := $podmac -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $DeletePlugins }}
  namespace: {{ .Values.jenkinsNodes.service.namespace }}
  annotations:
    "helm.sh/hook": "post-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
  template:
    metadata:
      annotations:
{{ dict "envAll" $envAll "podName" $DeletePlugins "containerNames" (list "check-plugins" ) | include "helm-toolkit.snippets.kubernetes_mandatory_access_control_annotation" | indent 8 }}
    spec:
      restartPolicy: Never
      serviceAccount: {{ $serviceAccountName }}
      containers:
      - name: check-plugins
        image: {{ .Values.images.tags.namespace_creator }}
        imagePullPolicy: {{ .Values.images.pull_policy }}
        command: ["/bin/sh","-c", "while [ $(kubectl get pods -n {{ .Values.jenkinsNodes.service.namespace }} jenkins-api-0 --no-headers -o custom-columns=':status.phase') != 'Running' ]; do echo 'Waiting for Jenkins POD to come running'; done; kubectl exec jenkins-api-0 -n {{ .Values.jenkinsNodes.service.namespace }} -- bash -c 'while [ ! -f /var/jenkins_home/plugins_downloaded ]; do echo \"Plugins are not downloaded yet...\"; done; echo \"Plugins are downloaded\"; if [ ! -d '/var/jenkins_home/plugins' ]; then echo \"Copying plugins backup to plugins folder\"; cp -r /var/jenkins_home/plugins_bkp /var/jenkins_home/plugins; fi'"]
