{{- $envAll := . }}

{{- $serviceAccountName := printf "create-namespace-%s" .Release.Name }}
{{- $DeletePlugins := printf "check-plugins-%s" .Release.Name }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $DeletePlugins }}
  namespace: {{ .Values.jenkinsNodes.service.namespace }}
  labels:
{{ tuple $envAll "check-plugins" "check-plugins" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 4 }}
  annotations:
    "helm.sh/hook": "post-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
  template:
    metadata:
      annotations:
{{ dict "envAll" $envAll "podName" "check-plugins" "containerNames" (list "check-plugins") | include "helm-toolkit.snippets.kubernetes_mandatory_access_control_annotation" | indent 8 }}
    spec:
      restartPolicy: Never
      serviceAccount: {{ $serviceAccountName }}
      containers:
      - name: check-plugins
        image: {{ .Values.images.tags.namespace_creator }}
        imagePullPolicy: {{ .Values.images.pull_policy }}
        command: ["/bin/sh","-c", "while [ \"$(kubectl get pods -n {{ .Values.jenkinsNodes.service.namespace }} jenkins-api-0 --no-headers -o custom-columns=':status.phase')\" != 'Running' ]; do echo 'Waiting for Jenkins POD to come running'; sleep 1; done; kubectl exec jenkins-api-0 -n {{ .Values.jenkinsNodes.service.namespace }} -- bash -c 'while [ ! -f /var/jenkins_home/plugins_downloaded ]; do echo \"Plugins are not downloaded yet...\"; done; echo \"Plugins are downloaded\"; if [ ! -d '/var/jenkins_home/plugins' ]; then echo \"Copying plugins backup to plugins folder\"; cp -r /var/jenkins_home/plugins_bkp /var/jenkins_home/plugins; fi'"]
