{{- if .Values.manifests.job_create_namespaces }}
{{- $envAll := . }}

{{- $serviceAccountName := printf "create-namespace-%s" .Release.Name }}
{{- $ImagePullSecret := printf "create-image-pull-secret-%s" .Release.Name }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $ImagePullSecret }}
  namespace: {{ .Values.jenkinsNodes.service.namespace }}
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
  template:
    spec:
      restartPolicy: Never
      serviceAccount: {{ $serviceAccountName }}
      containers:
      - name: image-pull-secret-add-sa
        image: {{ .Values.images.tags.namespace_creator }}
        imagePullPolicy: {{ .Values.images.pull_policy }}
        command: ["/bin/sh","-c", "kubectl patch serviceaccount default -p '{\"imagePullSecrets\": [{\"name\": \"{{ template "dockerconfigjson.name" . }}\"}]}' -n {{ .Values.jenkinsNodes.namespace }}"]
{{- end -}}
