{{- if .Values.conf.smart-proxy.enable -}}
{{- $envAll := . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- tuple $envAll "smart-proxy" "httpd" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | nindent 6 }}
  template:
    metadata:
      labels:
        {{- tuple $envAll "smart-proxy" "httpd" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | nindent 8 }}
      annotations:
        {{- if .Values.manifests.certificates }}
          {{- dict "envAll" $envAll "podName" "smart-proxy" "containerNames" (list "apache") | include "helm-toolkit.snippets.kubernetes_mandatory_access_control_annotation" | nindent 8}}
        {{- end }}
    spec:
      containers:
      - name: apache
        image: {{ .Values.images.tags.httpd }}
        ports:
        - containerPort: {{ .Values.conf.smart-proxy.port }}
        volumeMounts:
        - name: apache-config
          mountPath: /usr/local/apache2/conf/httpd.conf
          subPath: httpd.conf
      volumes:
      - name: apache-config
        configMap:
          name: smart-proxy-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: smart-proxy-config
data:
  httpd.conf: |
    ErrorLog /dev/stderr
    ServerRoot "/usr/local/apache2"
    Listen {{ .Values.conf.smart-proxy.port }}
    LoadModule mpm_event_module modules/mod_mpm_event.so
    LoadModule authz_core_module modules/mod_authz_core.so
    LoadModule proxy_module modules/mod_proxy.so
    LoadModule proxy_connect_module modules/mod_proxy_connect.so
    LoadModule unixd_module modules/mod_unixd.so
    PidFile /usr/local/apache2/logs/httpd.pid
    User daemon
    Group daemon
    ProxyRequests On
    ServerName smart-proxy
    <Proxy "*">
        Require all granted
    </Proxy>
    {{- range $rule := .Values.conf.smart-proxy.rules -}}
      {{- $rule | nident 4}}
    {{- end }}
    AllowCONNECT 443
---
apiVersion: v1
kind: Service
metadata:
  name: smart-proxy
spec:
  selector:
    {{- tuple $envAll "smart-proxy" "httpd" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | nindent 4 }}
  ports:
  - protocol: TCP
    port: {{ .Values.conf.smart-proxy.port }}
    targetPort: {{ .Values.conf.smart-proxy.port }}
{{- end -}}