{{- if and .Values.global.mongoUrl (not .Values.mongodb.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "xray.fullname" . }}-mongodb-secret
  labels:
    app: {{ template "xray.name" . }}
    chart: {{ template "xray.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{- if .Values.global.mongoUrl }}
      mongoUrl: {{ .Values.global.mongoUrl | b64enc | quote }}
  {{- end }}
{{- end }}