{{- if .Values.ingress.enabled -}}
{{- $serviceName := include "xray-server.fullname" . -}}
{{- $servicePort := .Values.server.externalPort -}}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ template "xray.fullname" . }}
  labels:
    app: {{ template "xray.name" . }}
    chart: {{ template "xray.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.ingress.labels }}
{{ .Values.ingress.labels | toYaml | trimSuffix "\n"| indent 4 -}}
{{- end}}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key }}: {{ tpl $value $ | quote }}
    {{- end }}
spec:
  {{- if .Values.ingress.defaultBackend.enabled }}
  backend:
    serviceName: {{ $serviceName }}
    servicePort: {{ $servicePort }}
  {{- end }}
  rules:
{{- if .Values.ingress.hosts }}
  {{- range $host := .Values.ingress.hosts }}
  - host: {{ $host | quote }}
    http:
      paths:
        - path: /
          {{- if (semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion) }}
          pathType: ImplementationSpecific
          {{- end }}
          backend:
          {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
            service:
              name: {{ $serviceName }}
              port:
                {{- if or (kindIs "int" $servicePort) (regexMatch "^[0-9]{1,5}$" $servicePort) }}
                number: {{ $servicePort | int }}
                {{- else }}
                name: {{ $servicePort | quote }}
                {{- end }}
          {{- else }}
            serviceName: {{ $serviceName }}
            servicePort: {{ $servicePort }}
          {{- end }}
  {{- end -}}
{{- end -}}
{{- with .Values.ingress.additionalRules }}
{{ tpl . $ | indent 2 }}
{{- end }}
  {{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}

