{{- if and (not .Values.systemYamlOverride.existingSecret) (not .Values.xray.unifiedSecretInstallation) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "xray.fullname" . }}-system-yaml
  labels:
    app: {{ template "xray.name" . }}
    chart: {{ template "xray.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
stringData:
  system.yaml: |
{{ tpl .Values.xray.systemYaml . | indent 4 }}
{{- end }}
