apiVersion: v1
appVersion: 2.6.0
description: Universal component scan for security and license inventory and impact
  analysis
home: https://www.jfrog.com/xray/
icon: https://raw.githubusercontent.com/jfrog/artifactory-dcos/master/images/jfrog_med.png
keywords:
- xray
- jfrog
maintainers:
- email: eldada@jfrog.com
  name: eldada
- email: jainishs@jfrog.com
  name: jainishshah17
- email: rimasm@jfrog.com
  name: rimusz
name: xray
sources:
- https://bintray.com/jfrog/product/xray/view
- https://github.com/jfrog/charts
version: 0.8.2
