dependencies:
- name: postgresql
  version: 9.3.4
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled
- name: rabbitmq-ha
  version: 1.46.4
  repository: https://charts.helm.sh/stable
  condition: rabbitmq-ha.enabled
