dependencies:
- name: postgresql
  version: 0.8.7
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: postgresql.enabled
- name: rabbitmq-ha
  version: 1.5.2
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: mongodb
  version: 2.0.5
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: mongodb.enabled
- name: helm-toolkit
  repository: http://localhost:8879/charts
  version: 0.1.0
