apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "insight-executor.fullname" . }}
  labels:
    app: {{ template "mission-control.name" . }}
    chart: {{ template "mission-control.chart" . }}
    component: {{ .Values.insightExecutor.name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.insightExecutor.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "mission-control.name" . }}
      component: {{ .Values.insightExecutor.name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "mission-control.name" . }}
        component: {{ .Values.insightExecutor.name }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ template "mission-control.serviceAccountName" . }}
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}
    {{- end }}
      securityContext:
        fsGroup: {{ .Values.uid }}
      initContainers:
      - name: "prepare-storage"
        image: "{{ .Values.initContainerImage }}"
        command:
        - 'sh'
        - '-c'
        - >
          mkdir -p {{ .Values.insightExecutor.persistence.mountPath }} ; 
          chown -R {{ .Values.uid }}:{{ .Values.uid }} {{ .Values.insightExecutor.persistence.mountPath }}
        volumeMounts:
        - name: insight-executor-data
          mountPath: {{ .Values.insightExecutor.persistence.mountPath | quote }}
      - name: "wait-for-db"
        image: "{{ .Values.initContainerImage }}"
        command:
        - 'sh'
        - '-c'
        - >
          until nc -z -w 2 {{ .Release.Name }}-mongodb 27017 && echo mongodb ok;
            do sleep 2;
          done;
          sleep 10
      containers:
      - name: {{ .Values.insightExecutor.name }}
        image: {{ .Values.insightExecutor.image }}:{{ default .Chart.AppVersion .Values.insightExecutor.version }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        env:
        - name: JFIS_URL
          value: 'http://{{ template "insight-server.fullname" . }}:{{ .Values.insightServer.internalHttpPort }}'
        - name: JFEX_LOGS
          value: '{{ .Values.insightExecutor.home }}/{{ .Values.insightExecutor.name }}/logs'
        - name: JFEX_APP_NAME
          value: '{{ .Values.insightExecutor.name }}'
        - name: MONGO_URL
          value: '{{ .Release.Name }}-mongodb:27017'
        - name: MONGODB_USERNAME
          value: '{{ .Values.mongodb.db.insightUser }}'
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "mission-control.fullname" . }}-mongodb-cred
              key: insightPassword
        - name: MONGODB_ADMIN_USERNAME
          value: '{{ .Values.mongodb.db.adminUser }}'
        - name: MONGODB_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "mission-control.fullname" . }}-mongodb-cred
              key: adminPassword
        - name: JFMC_EXECUTOR_MONGO_DB
          value: '{{ .Values.mongodb.db.insightExecutorDb }}'
        - name: JFMC_EXTRA_JAVA_OPTS
          value: "
          {{- if .Values.insightExecutor.javaOpts.other }}
              {{ .Values.insightExecutor.javaOpts.other }}
          {{- end}}
          {{- if .Values.insightExecutor.javaOpts.xms }}
              -Xms{{ .Values.insightExecutor.javaOpts.xms }}
          {{- end}}
          {{- if .Values.insightExecutor.javaOpts.xmx }}
              -Xmx{{ .Values.insightExecutor.javaOpts.xmx }}
          {{- end}}
          "
        ports:
        - containerPort: {{ .Values.insightExecutor.internalPort }}
          protocol: TCP
        volumeMounts:
        - name: insight-executor-data
          mountPath: {{ .Values.insightExecutor.persistence.mountPath | quote }}
        livenessProbe:
          httpGet:
            path: /executorservice/api
            port: {{ .Values.insightExecutor.internalPort }}
          initialDelaySeconds: 600
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /executorservice/api
            port: {{ .Values.insightExecutor.internalPort }}
          initialDelaySeconds: 600
          periodSeconds: 10
        resources:
{{ toYaml .Values.insightExecutor.resources | indent 10 }}
    {{- with .Values.insightExecutor.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.insightExecutor.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.insightExecutor.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
      - name: insight-executor-data
      {{- if .Values.insightExecutor.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ if .Values.insightExecutor.persistence.existingClaim }}{{ .Values.insightExecutor.persistence.existingClaim }}{{ else }}{{ template "insight-executor.fullname" . }}{{ end }}
      {{- else }}
        emptyDir: {}
      {{- end }}