apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "insight-server.fullname" . }}
  labels:
    app: {{ template "mission-control.name" . }}
    chart: {{ template "mission-control.chart" . }}
    component: {{ .Values.insightServer.name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.insightServer.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "mission-control.name" . }}
      component: {{ .Values.insightServer.name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "mission-control.name" . }}
        component: {{ .Values.insightServer.name }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ template "mission-control.serviceAccountName" . }}
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}
    {{- end }}
      securityContext:
        fsGroup: {{ .Values.uid }}
      initContainers:
      - name: "prepare-storage"
        image: "{{ .Values.initContainerImage }}"
        command:
        - 'sh'
        - '-c'
        - >
          mkdir -p {{ .Values.insightServer.persistence.mountPath }}  {{ .Values.insightServer.home }}/{{ .Values.insightServer.name }}/_MASTER_/data/contexts/security ;
          chown -R {{ .Values.uid }}:{{ .Values.uid }} {{ .Values.insightServer.persistence.mountPath }}
        volumeMounts:
        - name: insight-server-data
          mountPath: {{ .Values.insightServer.persistence.mountPath | quote }}
      - name: "wait-for-db"
        image: "{{ .Values.initContainerImage }}"
        command:
        - 'sh'
        - '-c'
        - >
          until nc -z -w 2 {{ .Release.Name }}-mongodb 27017 && echo mongodb ok && \
                nc -z -w 2 {{ .Release.Name }}-elasticsearch 9200 && echo elasticsearch ok;
            do sleep 2;
          done;
          sleep 40
      containers:
      - name: {{ .Values.insightServer.name }}
        image: {{ .Values.insightServer.image }}:{{ default .Chart.AppVersion .Values.insightServer.version }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        env:
        - name: JFIS_URL
          value: 'http://{{ template "insight-server.fullname" . }}:{{ .Values.insightServer.internalHttpPort }}'
        - name: JFEX_URL
          value: 'http://{{ template "insight-executor.fullname" . }}:{{ .Values.insightExecutor.internalPort }}'
        - name: JFSC_URL
          value: 'http://{{ template "insight-scheduler.fullname" . }}:{{ .Values.insightScheduler.internalPort }}'
        - name: JFIS_LOGS
          value: "{{ .Values.insightServer.home }}/{{ .Values.insightServer.name }}/logs"
        - name: JFIS_APP_NAME
          value: "{{ .Values.insightServer.name }}"
        - name: MONGO_URL
          value: '{{ .Release.Name }}-mongodb:27017'
        - name: MONGODB_USERNAME
          value: '{{ .Values.mongodb.db.insightUser }}'
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "mission-control.fullname" . }}-mongodb-cred
              key: insightPassword
        - name: MONGODB_ADMIN_USERNAME
          value: '{{ .Values.mongodb.db.adminUser }}'
        - name: MONGODB_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "mission-control.fullname" . }}-mongodb-cred
              key: adminPassword
        - name: JFMC_URL
          value: 'http://{{ template "mission-control.fullname" . }}:{{ .Values.missionControl.internalPort }}'
        - name: ELASTIC_SEARCH_URL
          value: 'http://{{ .Release.Name }}-elasticsearch:9200'
        - name: ELASTIC_SEARCH_WRITE_URL
          value: 'http://{{ .Release.Name }}-elasticsearch:9200'
        - name: ELASTIC_SEARCH_READ_URL
          value: 'http://{{ .Release.Name }}-elasticsearch:9200'
        - name: ELASTIC_LB_WRITE_URL
          value: ''
        - name: ELASTIC_LB_READ_URL
          value: ''
        - name: ELASTIC_CLUSTER_NAME
          value: '{{ .Values.elasticsearch.env.clusterName }}'
        - name: ELASTIC_SEARCH_USERNAME
          value: '{{ .Values.elasticsearch.env.esUsername }}'
        - name: ELASTIC_SEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-elasticsearch
              key: esPassword
        - name: JFMC_INSIGHT_SERVER_DB
          value: "{{ .Values.mongodb.db.insightServerDb }}"
        - name: JFIS_ALLOW_IP
          value: "{{ .Values.insightServer.allowIP }}"
        - name: JFMC_INSIGHT_SERVER_PORT
          value: "{{ .Values.insightServer.internalHttpPort }}"
        ports:
        - containerPort: {{ .Values.insightServer.internalHttpPort }}
          protocol: TCP
        volumeMounts:
        - name: insight-server-data
          mountPath: {{ .Values.insightServer.persistence.mountPath | quote }}
        livenessProbe:
          httpGet:
            path: /api/status
            port: {{ .Values.insightServer.internalHttpPort }}
          initialDelaySeconds: 600
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/status
            port: {{ .Values.insightServer.internalHttpPort }}
          initialDelaySeconds: 600
          periodSeconds: 10
        resources:
{{ toYaml .Values.insightServer.resources | indent 10 }}
    {{- with .Values.insightServer.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.insightServer.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.insightServer.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
      - name: insight-server-data
      {{- if .Values.insightServer.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ if .Values.insightServer.persistence.existingClaim }}{{ .Values.insightServer.persistence.existingClaim }}{{ else }}{{ template "insight-server.fullname" . }}{{ end }}
      {{- else }}
        emptyDir: {}
      {{- end }}