{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mission-control.fullname" . }}-postgresql-cred
  labels:
    app: {{ template "mission-control.name" . }}
    chart: {{ template "mission-control.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  jfisPassword:  {{ required "A valid .Values.postgresql.db.jfisPassword entry required!" .Values.postgresql.db.jfisPassword | b64enc | quote }}
  jfscPassword:  {{ required "A valid .Values.postgresql.db.jfscPassword entry required!" .Values.postgresql.db.jfscPassword | b64enc | quote }}
  jfexPassword:  {{ required "A valid .Values.postgresql.db.jfexPassword entry required!" .Values.postgresql.db.jfexPassword | b64enc | quote }}
  jfmcPassword:  {{ required "A valid .Values.postgresql.db.jfmcPassword entry required!" .Values.postgresql.db.jfmcPassword | b64enc | quote }}
  postgresPassword:  {{ required "A valid .Values.postgresql.postgresPassword entry required!" .Values.postgresql.postgresPassword | b64enc | quote }}
{{- end }}