{{- if .Values.manifests.secret_ingress_tls }}
{{- include "helm-toolkit.manifests.secret_ingress_tls" ( dict "envAll" . "backendServiceType" "missioncontrol" "backendService" "missioncontrol" ) }}
{{- end }}
